---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 735473639286509569-QnRV1jNKaTkn8EqI0lMzQeo52ndeYu2
:access_token_secret: uAQNO8cAd7LKv2YsJYTJ7ojwsDUloJo08dodgNeZwqpwY
